# Generated by Django 4.1.3 on 2022-11-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
