# Generated by Django 4.1.3 on 2022-11-27 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0008_rename_active_status_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creation_date', models.DateField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('url_image', models.CharField(max_length=100)),
                ('url_destiny', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url_store', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('url_picture', models.CharField(max_length=100)),
                ('url_product', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('id_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.stores')),
            ],
        ),
    ]
