# Generated by Django 4.1.3 on 2022-11-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0009_news_stores_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price_sale',
            field=models.FloatField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
