# Generated by Django 4.1.3 on 2022-12-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0012_rename_creation_date_news_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
