# Generated by Django 4.1.3 on 2023-01-11 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='basic.people'),
        ),
    ]
