# Generated by Django 4.1.3 on 2023-01-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_alter_users_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
