# Generated by Django 4.1.3 on 2022-11-25 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('id_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.people')),
                ('id_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.roles')),
                ('id_statis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.status')),
            ],
        ),
    ]
