# Generated by Django 4.1.3 on 2023-01-11 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_productregisters'),
        ('basic', '0004_googleusers'),
    ]

    operations = [
    ]
