# Generated by Django 4.1.3 on 2022-11-25 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='id_statis',
            new_name='id_status',
        ),
    ]
