# Generated by Django 4.1.3 on 2022-11-25 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0006_rename_id_statis_users_id_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='active',
            field=models.CharField(max_length=100),
        ),
    ]
