# Generated by Django 4.1.3 on 2023-01-11 21:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_merge_0002_productregisters_0004_googleusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
