# Generated by Django 4.1.3 on 2023-01-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0007_products_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='view_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
