# Generated by Django 4.1.3 on 2023-01-11 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0009_products_view_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='view_num',
        ),
    ]
