# Generated by Django 4.1.3 on 2022-12-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0011_rename_id_store_products_store_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='creation_date',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='mail',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='news',
            name='url_destiny',
        ),
        migrations.RemoveField(
            model_name='news',
            name='url_image',
        ),
        migrations.AddField(
            model_name='news',
            name='cover',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='redirect',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
