# Generated by Django 4.1.3 on 2023-01-11 22:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0010_remove_products_view_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='productregisters',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
