# Generated by Django 4.1.4 on 2023-01-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0012_productregisters_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='imageUrl',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
