# Generated by Django 4.1.4 on 2023-01-13 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0013_users_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='imageUrl',
        ),
    ]
