# Generated by Django 4.1.3 on 2022-12-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0013_alter_news_description_alter_products_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='creation_date',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='view_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='price_sale',
            field=models.FloatField(blank=True, max_length=100),
        ),
    ]
