# Generated by Django 4.1.3 on 2022-12-08 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0014_googleusers_products_creation_date_products_view_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='identification',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='stores',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='stores',
            name='url_store',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.people', unique=True),
        ),
    ]
