# Generated by Django 4.1.4 on 2023-01-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0017_alter_users_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price_sale',
            field=models.FloatField(max_length=100, null=True),
        ),
    ]
