# Generated by Django 4.1.4 on 2023-01-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0018_alter_products_price_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='url_picture',
            new_name='cover',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='price_sale',
            new_name='priceSale',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='url_product',
            new_name='redirect',
        ),
        migrations.AddField(
            model_name='products',
            name='colors',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
