# Generated by Django 4.1.4 on 2023-01-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0020_alter_productregisters_redirect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productregisters',
            name='redirect',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productregisters',
            name='visits',
            field=models.IntegerField(),
        ),
    ]
