# Generated by Django 4.1.4 on 2023-01-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0022_alter_products_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='redirect',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
